package.json
public/favicon/manifest.json
src/pages/_app.tsx
src/pages/index.tsx
src/styles/globals.css
yarn.lock

feat: add tooltip to copy button

---

src/pages/ingfo.tsx

feat: changed custom link to left arrowlink

---

src/data/dataMatkul.ts
src/pages/index.tsx

feat: search matkul

---

src/components/Troubleshoot.tsx
src/pages/api/matkul.ts
src/pages/api/matkul/[kode].ts
src/pages/index.tsx

feat: more subtle info i guess

---

README.md

docs: repo size

---

src/pages/index.tsx

fix: accessibility color issue

---

src/components/Nav.tsx

fix: accessibility only li are allowed inside ul

---

src/components/Contact.tsx
src/pages/404.tsx
src/pages/ingfo.tsx

feat: contact

---

src/components/Seo.tsx

fix: missing favicon

---

package.json
src/components/Nav.tsx
src/lib/escapeRegex.ts
src/pages/api/matkul.ts
yarn.lock

feat: add repo link in the navbar

---

src/pages/_document.tsx

feat: add umami analytics

---

package.json
src/pages/_app.tsx
yarn.lock

feat: add hotjar

---

src/pages/index.tsx

refactor: remove useEffect

---

src/components/Footer.tsx

feat: change copyright

---

package.json
yarn.lock

feat: add sharp package

---

src/components/Code.tsx
src/components/Nav.tsx
src/components/Troubleshoot.tsx
src/pages/apidocs.tsx
src/pages/index.tsx
src/pages/ingfo.tsx

feat: add api docs route

---

package.json
src/components/content/Comment.tsx
src/pages/index.tsx
yarn.lock

feat: add comment section

---

src/pages/index.tsx
src/pages/ingfo.tsx

feat: add comment section on ingfo page

---

src/pages/_app.tsx

fix: not initializing hotjar if not on main domain

---

README.md

docs: add license badge

---

src/pages/ingfo.tsx
src/styles/globals.css
tailwind.config.js

refactor: use new rgba format

---

.github/workflows/cypress.yml
package.json
src/pages/_app.tsx
src/styles/nprogress.css
yarn.lock

feat: add nprogress

---

src/pages/index.tsx

feat: update kelas trnyata bisa angka

---

src/pages/index.tsx

feat: better ux, mayhaps

---

package.json
src/pages/index.tsx
yarn.lock

feat: using react select for better select input

---

src/pages/index.tsx

feat: add query string to set matkul, kelas, and semester

---

src/pages/index.tsx

feat: add query string for mkSem and mkThn

---

package.json
yarn.lock

chore: add standard version
